accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
     path('', views.my_profile, name='my_profile'),
]

bookstore_app/urls.py
from django.urls import path
from . import views

app_name = 'bookstore_app'

urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('make_author/', views.make_author, name='make_author')
]

my_bookstore/urls.py
from my_bookstore.settings import DEBUG
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from bookstore_app import views
import bookstore_app
import accounts
import shopping_cart

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.book_list, name='book_list'),
    path('books/', include('bookstore_app.urls', namespace='bookstore_app')),
    path('cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    path('profiles/', include('accounts.urls', namespace='profile')),
    path('accounts/', include('allauth.urls')),
    # stripe urls
    path('success/', shopping_cart.views.success, name='success')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shopping_cart/urls.py
from django.urls import path
from . import views

app_name = 'shopping_cart'

urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('delete-from-cart/<int:pk>/', views.del_from_cart, name='del_from_cart'),
    path('cart-details', views.cart_details, name='cart-details'),
    path('checkout/', views.checkout, name='checkout'),
    path('process-payment/<order_id>', views.process_payment, name='process-payment'),
    path('update_records/<int:order_id>/', views.update_transaction_record, name='update-records'),
]

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</body>
</html>

templates/book_list.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center">This is the home page!</h1>

{% for book in books %}
{% if book in current_books %}
<div class="card">
    <div class="card-header">
        {{book.title}}
    </div>
    <img src="{{book.cover.url}}" height="300px" width="300px" alt="...">
    <div class="card-body">
        <h5 class="card-title"><b>Title:</b> {{book.title}}</h5>
        <p>item in cart</p>
        <h5 class="card-subtitle"><b>Genre:</b> {{book.genre}}</h5>
        <hr/>
        <p class="card-text">{{book.body}}</p>
        <h6 style="color: green;">${{book.price}}</h6>
        <a href="#" class="btn btn-primary">sneak peak</a>
    </div>
  </div>
  <br/>
{% elif book in request.user.profile.my_ebooks.all %}
<div class="card">
    <div class="card-header">
        {{book.title}}
    </div>
    <img src="{{book.cover.url}}" height="300px" width="300px" alt="...">
    <div class="card-body">
        <h5 class="card-title"><b>Title:</b> {{book.title}}</h5>
        <h5 class="card-subtitle"><b>Genre:</b> {{book.genre}}</h5>
        <p>already bought</p>
        <hr/>
        <p class="card-text">{{book.body}}</p>
        <h6 style="color: green;">${{book.price}}</h6>
        <a href="#" class="btn btn-primary">sneak peak</a>
    </div>
  </div>
  <br/>
{% else %}
<div class="card">
    <div class="card-header">
        {{book.title}}
    </div>
    <img src="{{book.cover.url}}" height="300px" width="300px" alt="...">
    <div class="card-body">
        <h5 class="card-title"><b>Title:</b> {{book.title}}</h5>
        <h5 class="card-subtitle"><b>Genre:</b> {{book.genre}}</h5>
        <a href="{% url 'shopping_cart:add_to_cart' book.id %}">add_to_cart</a>
        <hr/>
        <p class="card-text">{{book.body}}</p>
        <h6 style="color: green;">${{book.price}}</h6>
        <a href="#" class="btn btn-primary">sneak peak</a>
    </div>
  </div>
  <br/>
{% endif %}
{% endfor %}

{% endblock content %}

templates/cart_detail.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center">Your cart</h1>

<div class="row" style="margin-left: 1.5in;">
{% for item in current_order.items.all  %}
<div class="card text-center" style="margin-left: .3in; width: 18rem;">
  <img src="{{item.book.cover.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h3 class="card-title">{{item.book.title}}</h3>
    <h5 class="card-subtitle">${{item.book.price}}</h5>
    <a href="{%url 'shopping_cart:del_from_cart' item.id %}"><button class="btn btn-danger">remove</button></a>
  </div>
</div>
{% endfor %}
</div>

<h3 class="text-center">Total is ${{current_order.get_cart_total}}</h3>
<form action="{% url 'shopping_cart:process-payment' current_order.id %}" method="POST">
  {% csrf_token %}
  <div class="text-center">
  <button class="btn btn-primary" type="submit">Procede to Checkout</button>
  </div>
</form>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center">Your cart</h1>

<div class="row" style="margin-left: 1.5in;">
{% for item in current_order.items.all  %}
<div class="card text-center" style="margin-left: .3in; width: 18rem;">
  <img src="{{item.book.cover.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h3 class="card-title">{{item.book.title}}</h3>
    <h5 class="card-subtitle">${{item.book.price}}</h5>
  </div>
</div>
{% endfor %}
</div>

<h3 class="text-center">Total is ${{current_order.get_cart_total}}</h3>
<form action="{% url 'shopping_cart:process-payment' current_order.id %}" method="POST">
  {% csrf_token %}
  <div class="text-center">
  <button class="btn btn-primary" type="submit">Procede to Checkout</button>
  </div>
</form>
{% endblock %}

templates/my_profile.html
this is the profile view!
{% for book in my_pro.my_ebooks.all %}
{{book.title}}
{% endfor %}
{% if my_pro.my_ebooks.all == None %}
{{message}}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'bookstore_app:book_list' %}">Browse</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile:my_profile' %}">dashboard</a>
          </li>
         
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopping_cart:cart-details' %}">my-cart</a>
          </li>
          {% if user.groups.all %}
          {% if 'Author' %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'shopping_cart:cart-details' %}">Add a book</a>
        </li>
          {% endif %}
          {% endif %}
          {% endif %}
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        <form  method="POST" action="{% url 'bookstore_app:make_author'%}">
          {% csrf_token %}
           <label for="author">want to be an author!</label>
          <input type="checkbox" name="author">
          <button class="btn btn-outline-success" type="submit">Click here!</button>
        </form>
      </div>
    </div>
  </nav>

templates/success.html
<h1>Your payment was succesfull! an email was sent!</h1>